export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const ADD_MOVIES_TO_FAVOURITE = 'ADD_MOVIES_TO_FAVOURITE';
export const REMOVE_MOVIES_FROM_FAVOURITE = 'REMOVE_MOVIES_FROM_FAVOURITE';
export const UPDATE_FAVOURITE_MOVIES = 'UPDATE_FAVOURITE_MOVIES';
export const ADD_MOVIES_TO_ALL = 'ADD_MOVIES_TO_ALL';
export const REMOVE_MOVIES_FROM_ALL = 'REMOVE_MOVIES_FROM_ALL';
